name: pipenline build and push modern
on:
  push:
    branches: [main]

jobs:
  tests1:
    runs-on: ubuntu-latest
    steps:
      - name: code lao
        uses: actions/checkout@v4
  build-and-push:
    needs: tests1
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4

      - name: docker login
        uses: docker/login-actions@v4
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name:  login and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/myapp19sep:latest
